### ISSUE TITLE
Stemmer Choice

### ISSUE THREAD

**Issue by AlexanderDavid** [kk7nc/Text_Classification#10]
The snowball stemmer (also known as Porterv2) is commonly accepted as the superior choice when it comes to stemming. Is there any reason you chose to use the Porter stemmer in your examples?

**Comment by kk7nc** [comment]
Thank you for the question, no reason for using Porter Stemmer just is an example, but you can add it and send a pull request we are happy to accept other examples and make the repository stronger.
