### ISSUE TITLE
There is a error about CBOW and skip-gram picture

### ISSUE THREAD

**Issue by yucc2018** [kk7nc/Text_Classification#2]
In the  following picture, there is a error.
https://github.com/kk7nc/Text_Classification/blob/master/docs/pic/CBOW.png

The left picture is CBOW and the right picture is skip-gram according to the figure  1 in  _Distributed Representations of Words and Phrases and their Compositionality._

**Comment by kk7nc** [comment]
Thank you for your consideration,
It's fixed,
Best,
Kamran
